src/test/java/com/speech/up/script/controller/ScriptControllerTest.java
src/test/java/com/speech/up/script/entity/ScriptEntityTest.java
src/test/java/com/speech/up/script/service/ScriptServiceTest.java
src/test/java/com/speech/up/user/controller/UserControllerTest.java
src/test/java/com/speech/up/user/entity/UserEntityTest.java
src/test/java/com/speech/up/user/service/UserServiceTest.java

[#8] Feat: ScriptService test code complete

---

src/main/java/com/speech/up/script/controller/ScriptController.java
src/main/java/com/speech/up/script/repository/ScriptRepository.java
src/main/java/com/speech/up/script/service/ScriptService.java

[#9] feat : add feature(create,update,delete)

[#9] feat : add feature(create,update,delete)

---

src/main/java/com/speech/up/script/controller/ScriptController.java
src/main/java/com/speech/up/script/repository/ScriptRepository.java
src/main/java/com/speech/up/script/service/ScriptService.java

[#9] fixed : add feature(create,update,delete)

[#9] fixed : add feature(create,update,delete)

---

src/main/java/com/speech/up/script/entity/ScriptEntity.java
src/main/java/com/speech/up/user/entity/UserEntity.java

[#16] Fixed : 엔티티 중복 현상 수정

---

src/main/java/com/speech/up/script/entity/ScriptEntity.java
src/main/java/com/speech/up/user/entity/UserEntity.java

[#16] Fixed : 엔티티 중복 현상 다시 수정합니다.

---

src/main/java/com/speech/up/user/entity/UserEntity.java
src/test/java/com/speech/up/script/controller/ScriptControllerTest.java
src/test/java/com/speech/up/script/entity/ScriptEntityTest.java

- script 조회 기능 테스트 완료
- script entity 테스트 완료

[#10] Feature : script 조회 기능, scriptEntity 테스트 구현 완료

---

src/main/java/com/speech/up/script/controller/ScriptController.java
src/main/java/com/speech/up/script/repository/ScriptRepository.java
src/main/java/com/speech/up/script/service/ScriptService.java
src/main/java/com/speech/up/user/entity/UserEntity.java
src/test/java/com/speech/up/user/entity/UserEntityTest.java

- UserEntity test code 작성 및 테스트 완료
- Controller 및 Service 주석 설명 추가

[#20] Feature : UserEntity 테스트 구현 완료

---

src/main/resources/application-test.yaml
src/test/java/com/speech/up/script/repository/ScriptRepositoryTest.java
src/test/java/com/speech/up/script/service/ScriptServiceTest.java

- 레포지토리 테스트 간 [#22 ] 버그 발견, 데이터 베이스 수정 요구.

[#10] 서비스 테스트 추가 & [#11] 레포지토리 테스트 추가

---

src/main/java/com/speech/up/script/service/ScriptService.java

- 대본 수정 시 생성일자가 바뀌는 현상을 수정하였습니다.

[#25] Fix : 대본 수정기능 수정

---

src/main/java/com/speech/up/script/service/ScriptService.java

[#25] Fix : 대본 수정기능 수정(2)

---

src/main/resources/static/css/record-style.css
src/main/resources/static/js/record.js
src/main/resources/templates/record.html

- 녹음 기능 테스트 할 페이지 구현했습니다. 자유롭게 바꿔서 쓰시면 됩니다.

[#31] Feat: 녹음 테스트 페이지 구현

---

src/main/java/com/speech/up/script/controller/ScriptController.java
src/main/java/com/speech/up/script/entity/ScriptEntity.java
src/main/java/com/speech/up/script/repository/ScriptRepository.java
src/main/java/com/speech/up/script/service/ScriptService.java
src/main/java/com/speech/up/script/service/dto/ScriptGetDto.java
src/main/java/com/speech/up/script/service/dto/ScriptUpdateDto.java
src/test/java/com/speech/up/script/controller/ScriptControllerTest.java
src/test/java/com/speech/up/script/entity/ScriptEntityTest.java
src/test/java/com/speech/up/script/repository/ScriptRepositoryTest.java
src/test/java/com/speech/up/script/service/ScriptServiceTest.java

[#36] Feat!: 코드 리팩토링 및 DTO 생성

---

src/main/java/com/speech/up/script/controller/ScriptController.java
src/main/java/com/speech/up/script/entity/ScriptEntity.java
src/main/java/com/speech/up/script/repository/ScriptRepository.java
src/main/java/com/speech/up/script/service/ScriptService.java
src/main/java/com/speech/up/script/service/dto/ScriptGetDto.java
src/main/java/com/speech/up/script/service/dto/ScriptUpdateDto.java

- Raw 를 삭제하는 방식이 아닌 Flag 방식으로 변경

[#36] Fix : Raw 를 삭제하는 방식 -> Flag 방식으로 변경

---

src/main/java/com/speech/up/script/service/dto/ScriptAddDto.java
src/main/java/com/speech/up/script/service/dto/ScriptIsUseDto.java

ScriptIsUseDto 파일과  ScriptAddDto 파일 누락되어 다시 올립니다.  죄송합니다.

[#36] Fix : 누락 파일 재 업로드

---

src/main/java/com/speech/up/script/controller/RecordController.java
src/main/java/com/speech/up/script/controller/ScriptController.java
src/main/java/com/speech/up/script/entity/RecordEntity.java
src/main/java/com/speech/up/script/entity/ScriptEntity.java
src/main/java/com/speech/up/script/repository/RecordRepository.java
src/main/java/com/speech/up/script/repository/ScriptRepository.java
src/main/java/com/speech/up/script/service/RecordService.java
src/main/java/com/speech/up/script/service/ScriptService.java
src/main/java/com/speech/up/script/service/dto/RecordAddDto.java
src/main/java/com/speech/up/script/service/dto/RecordGetDto.java
src/main/java/com/speech/up/script/service/dto/RecordIsUseDto.java
src/test/java/com/speech/up/script/service/ScriptServiceTest.java

- 녹음 Entity
- 녹음 생성 Controller, Service, Repository, Dto
- 녹음 조회 Controller, Service, Repository, Dto
- 녹음 삭제 Controller, Service, Repository, Dto

[#40] 녹음 생성, 조회, 삭제 기능 추가

---

src/main/java/com/speech/up/user/controller/UserController.java
src/main/java/com/speech/up/user/entity/UserEntity.java
src/main/java/com/speech/up/user/service/UserService.java
src/main/java/com/speech/up/user/service/dto/UserGetInfoDto.java
src/test/java/com/speech/up/user/entity/UserEntityTest.java

- UserEntityTest 구현 완료
- 조회 Controller, service, dto 생성 및 Entity 수정

[#42] 유저 정보 조회 기능 구현

---

src/main/resources/application-test.yaml
src/test/java/com/speech/up/script/controller/ScriptControllerTest.java
src/test/java/com/speech/up/script/entity/ScriptEntityTest.java
src/test/java/com/speech/up/script/repository/ScriptRepositoryTest.java

[ ] ScriptController 테스트 코드 작성
[ ] ScriptRepository 테스트 코드 작성 
[ ] ScriptEntity 테스트 코드 작성

[#36] 테스트 코드 작성

---

src/main/java/com/speech/up/customException/CustomIllegalAccessException.java
src/main/java/com/speech/up/customException/CustomIoException.java
src/main/java/com/speech/up/globalException/ErrorResponse.java
src/main/java/com/speech/up/globalException/GlobalException.java
src/main/java/com/speech/up/script/service/recordFile/RecordFile.java

[#46] 글로벌, 커스텀 예외처리 추가

---

src/main/java/com/speech/up/demo/HomePageController.java
src/main/java/com/speech/up/demo/ScriptPageController.java
src/main/resources/static/js/record.js
src/main/resources/templates/home.html
src/main/resources/templates/script.html

[#49] fix : 페이지 코드 수정

---

src/main/java/com/speech/up/UpApplication.java
src/main/java/com/speech/up/customException/TaskIdIsNullException.java
src/main/java/com/speech/up/globalException/GlobalException.java
src/main/java/com/speech/up/script/controller/RecordController.java
src/main/java/com/speech/up/script/controller/ScriptController.java
src/main/java/com/speech/up/script/entity/BaseRecordEntity.java
src/main/java/com/speech/up/script/entity/BaseScriptEntity.java
src/main/java/com/speech/up/script/entity/RecordEntity.java
src/main/java/com/speech/up/script/entity/ScriptEntity.java
src/main/java/com/speech/up/script/service/RecordService.java
src/main/java/com/speech/up/script/service/ScriptService.java
src/main/java/com/speech/up/script/service/dto/RecordAddDto.java
src/main/java/com/speech/up/script/service/dto/RecordGetDto.java
src/main/java/com/speech/up/script/service/dto/RecordIsUseDto.java
src/main/java/com/speech/up/script/service/dto/ScriptAddDto.java
src/main/java/com/speech/up/script/service/dto/ScriptGetDto.java
src/main/java/com/speech/up/script/service/dto/ScriptIsUseDto.java
src/main/java/com/speech/up/script/service/dto/ScriptUpdateDto.java
src/test/java/com/speech/up/script/entity/ScriptEntityTest.java
src/test/java/com/speech/up/script/repository/ScriptRepositoryTest.java

- 코드 리팩토링 중입니다. 추가 수정이 필요합니다.
- 전체적으로 코딩 컨벤션 적용 했습니다.
- 추가 수정 필요 부분
- 업데이트 동작 중 created_at 이 db 에는 정상이지만, response 값으로는 null 값으로 뜨는 현상
- 테스트 코드 리팩토링 필요.
- 도메인 수정 필요.

[#36] fix! : 임시 코드 리팩토링

---

src/main/java/com/speech/up/oAuth/common/ResponseMessage.java
src/main/java/com/speech/up/oAuth/repository/CertificationRepository.java

[#55] feature : 누락 파일 업로드

---

src/main/java/com/speech/up/oAuth/config/WebSecurityConfig.java

- 시큐리티 설정 오류로 버그가 발생 
- 리다이렉트 uri 설정
- token 확인 완료
- db 저장 확인 완료

[#59] Fixed : 시큐리티 설정  변경을 통한 버그 해결

---

src/main/java/com/speech/up/oAuth/filter/JwtAuthenticationFilter.java
src/main/java/com/speech/up/oAuth/handler/OAuth2SuccessHandler.java
src/main/java/com/speech/up/oAuth/service/implement/OAuth2UserServiceImplement.java
src/main/java/com/speech/up/oAuth/service/implement/OAuthServiceImplement.java
src/main/java/com/speech/up/script/controller/ScriptController.java
src/main/java/com/speech/up/user/controller/UserController.java
src/main/java/com/speech/up/user/entity/UserEntity.java
src/main/java/com/speech/up/user/service/UserService.java
src/main/java/com/speech/up/user/service/dto/UserGetInfoDto.java
src/main/resources/static/scriptPage/js/scriptList.js
src/main/resources/templates/home.html

사용자 정보를 세션에 저장하고 불러오는 기능을 구현하였습니다. 
userController를 일부 수정 하였습니다.

[#61] 사용자 정보 세션 저장 기능 구현

---

src/main/java/com/speech/up/board/controller/BoardController.java
src/main/java/com/speech/up/board/entity/BaseBoardEntity.java
src/main/java/com/speech/up/board/entity/BoardEntity.java
src/main/java/com/speech/up/board/repository/BoardRepository.java
src/main/java/com/speech/up/board/service/BoardService.java
src/main/java/com/speech/up/board/service/dto/BoardAddDto.java
src/main/java/com/speech/up/board/service/dto/BoardGetDto.java
src/main/java/com/speech/up/board/service/dto/BoardIsUseDto.java
src/main/java/com/speech/up/board/service/dto/BoardUpdateDto.java
src/main/java/com/speech/up/user/entity/UserEntity.java

- 메소드 명 수정
- 삭제 시 content와 Title이 필요 한 이유는 해당 테이블을 삭제하는 것이 아닌 use 플래그로 미사용 여부만 결정하기 때문입니다.
- 만약 null 값으로 하려고 해도 nullable check에서 throw 되기 때문에 "" 값으로 두어야하는데 차라리 기존 값을 클라이언트로부터 받아 use만 변경하는 것이 좋을 것 같습니다.

[#69] Board 기능 구현

---

build/resources/main/application.yaml
src/main/java/com/speech/up/UpApplication.java
src/main/java/com/speech/up/api/etri/controller/TestController.java
src/main/java/com/speech/up/api/etri/dto/RequestVoiceToTextApiDto.java
src/main/java/com/speech/up/api/etri/dto/ResponseVoiceToTextApiDto.java
src/main/java/com/speech/up/api/etri/service/ApiType.java
src/main/java/com/speech/up/api/etri/service/ApiUrl.java
src/main/java/com/speech/up/api/etri/service/PronunciationAI.java
src/main/java/com/speech/up/api/etri/service/RecognizedAI.java
src/main/java/com/speech/up/api/etri/service/UrlCollector.java
src/main/java/com/speech/up/api/etri/service/VoiceToTextService.java
src/main/resources/application.yaml

- 추후 리팩토링을 통해서 메서드 분리가 요망되는 코드 입니다. 
- 현재 인터페이스는 Pronunciation과 Recognized를 분기처리 하고 있습니다.

[#76] Etri AI 요청 기능 추가

---

src/main/java/com/speech/up/api/etri/controller/TestController.java
src/main/java/com/speech/up/api/etri/dto/AiRequest.java
src/main/java/com/speech/up/api/etri/dto/RequestVoiceToTextApiDto.java
src/main/java/com/speech/up/api/etri/dto/ResponseVoiceToTextApiDto.java
src/main/java/com/speech/up/api/etri/service/VoiceToTextService.java

[#76] Etri AI 요청 기능 추가 - body 수정

---

src/main/resources/static/css/record-style.css
src/main/resources/static/scriptPage/js/addRecordingToList.js
src/main/resources/static/scriptPage/js/record.js
src/main/resources/static/scriptPage/js/saveRecord.js
src/main/resources/templates/script.html

[#82] 녹음 추가

---

src/main/java/com/speech/up/api/speechFlow/service/VoiceToTextSpeechFlowService.java
src/main/java/com/speech/up/demo/HomePageController.java
src/main/java/com/speech/up/demo/ScriptPageController.java
src/main/java/com/speech/up/oAuth/config/WebSecurityConfig.java
src/main/java/com/speech/up/oAuth/filter/JwtAuthenticationFilter.java
src/main/java/com/speech/up/oAuth/handler/OAuth2SuccessHandler.java
src/main/java/com/speech/up/oAuth/service/implement/OAuth2UserServiceImplement.java
src/main/java/com/speech/up/script/controller/ScriptController.java
src/main/java/com/speech/up/script/service/ScriptService.java
src/main/java/com/speech/up/user/controller/UserController.java
src/main/java/com/speech/up/user/entity/UserEntity.java
src/main/java/com/speech/up/user/service/UserService.java
src/main/java/com/speech/up/user/service/dto/UserGetInfoDto.java
src/main/resources/static/scriptPage/js/addTokenSession.js
src/main/resources/static/scriptPage/js/scriptList.js
src/main/resources/static/scriptPage/js/scriptWrite.js
src/main/resources/static/scriptPage/js/userMe.js
src/main/resources/templates/home.html
src/main/resources/templates/script-list.html
src/main/resources/templates/script-write.html

session 제거 및 token 사용.
refresh token 미구현

[#55] OAuth session 제거

---

build/resources/main/application.yaml
src/main/java/com/speech/up/UpApplication.java
src/main/java/com/speech/up/api/etri/dto/AiRequest.java
src/main/java/com/speech/up/api/etri/service/ApiType.java
src/main/java/com/speech/up/api/etri/service/VoiceToTextService.java
src/main/java/com/speech/up/api/etri/type/ApiType.java
src/main/java/com/speech/up/api/etri/url/ApiUrl.java
src/main/java/com/speech/up/api/etri/url/PronunciationAI.java
src/main/java/com/speech/up/api/etri/url/RecognizedAI.java
src/main/java/com/speech/up/api/etri/url/UrlCollector.java
src/main/java/com/speech/up/oAuth/entity/CustomOAuth2User.java
src/main/java/com/speech/up/oAuth/provider/GithubProvider.java
src/main/java/com/speech/up/oAuth/provider/GoogleProvider.java
src/main/java/com/speech/up/oAuth/provider/KakaoProvider.java
src/main/java/com/speech/up/oAuth/provider/Provider.java
src/main/java/com/speech/up/oAuth/provider/ProviderOAuth.java
src/main/java/com/speech/up/oAuth/service/implement/OAuth2UserServiceImplement.java
src/main/java/com/speech/up/oAuth/service/implement/UserAuthorizationType.java
src/main/java/com/speech/up/oAuth/service/servicetype/LevelType.java
src/main/java/com/speech/up/oAuth/service/servicetype/ProviderType.java
src/main/resources/application.yaml

[#55] OAuth 카카오, 깃허브 로그인 추가

---

src/main/java/com/speech/up/board/controller/BoardController.java
src/main/java/com/speech/up/board/entity/BoardEntity.java
src/main/java/com/speech/up/board/repository/BoardRepository.java
src/main/java/com/speech/up/board/service/BoardService.java
src/main/java/com/speech/up/board/service/checkValue/CheckListForPagination.java
src/main/java/com/speech/up/board/service/checkValue/CheckParamForPagination.java
src/main/java/com/speech/up/board/service/dto/BoardGetDto.java
src/main/java/com/speech/up/board/service/dto/BoardIsUseDto.java
src/main/java/com/speech/up/user/entity/UserEntity.java

board의 페이지네이션 추가했습니다. 
board entity 변경
social_id -> user_id bigint not null 추가 바랍니다. 
userEntity의 id에 컬럼명을 추가했습니다.

[#69] board pagination 검색 기능 추가

---

build/resources/main/application.yaml
src/main/java/com/speech/up/board/controller/BoardController.java
src/main/java/com/speech/up/board/repository/BoardRepository.java
src/main/java/com/speech/up/board/service/BoardService.java
src/main/java/com/speech/up/board/service/checkValue/CheckListForPagination.java
src/main/java/com/speech/up/demo/BoardPageController.java
src/main/java/com/speech/up/user/service/UserService.java
src/main/resources/static/scriptPage/js/boardWrite.js
src/main/resources/static/scriptPage/js/checkLogined.js
src/main/resources/static/scriptPage/js/userMe.js
src/main/resources/templates/board-detail.html
src/main/resources/templates/board-edit.html
src/main/resources/templates/board.html

자유게시판 추가하기 및 삭제하기

---

src/main/java/com/speech/up/reply/controller/ReplyController.java
src/main/java/com/speech/up/reply/entity/ReplyEntity.java
src/main/java/com/speech/up/reply/repository/ReplyRepository.java
src/main/java/com/speech/up/reply/service/ReplyService.java
src/main/java/com/speech/up/reply/service/dto/ReplyGetDto.java
src/main/resources/static/scriptPage/js/reply.js
src/main/resources/static/scriptPage/js/userMe.js
src/main/resources/templates/board-detail.html

[#72] 자유게시판 기능 구현, 댓글 추가

---

src/main/java/com/speech/up/demo/HomePageController.java
src/main/java/com/speech/up/user/controller/UserController.java
src/main/java/com/speech/up/user/repository/UserRepository.java
src/main/java/com/speech/up/user/service/UserService.java
src/main/java/com/speech/up/user/service/dto/UserGetInfoDto.java
src/main/resources/static/css/my-page.css
src/main/resources/static/scriptPage/js/userDelete.js
src/main/resources/static/scriptPage/js/userMe.js
src/main/resources/templates/myPage.html

[#102] 마이페이지 프론트, 회원 탈퇴 기능 구현

---

src/main/java/com/speech/up/board/controller/BoardController.java
src/main/java/com/speech/up/board/repository/BoardRepository.java
src/main/java/com/speech/up/board/service/BoardService.java
src/main/java/com/speech/up/demo/BoardPageController.java
src/main/java/com/speech/up/reply/controller/ReplyController.java
src/main/java/com/speech/up/reply/repository/ReplyRepository.java
src/main/java/com/speech/up/reply/service/ReplyService.java
src/main/java/com/speech/up/script/controller/ScriptController.java
src/main/java/com/speech/up/script/repository/ScriptRepository.java
src/main/java/com/speech/up/script/service/ScriptService.java
src/main/resources/static/css/header-style.css
src/main/resources/static/css/land-style.css
src/main/resources/static/scriptPage/js/boardCount.js
src/main/resources/static/scriptPage/js/reply.js
src/main/resources/static/scriptPage/js/replyCount.js
src/main/resources/static/scriptPage/js/scriptCount.js
src/main/resources/static/scriptPage/js/userMe.js
src/main/resources/templates/home.html
src/main/resources/templates/myPage.html

자기 자신의 각 게시글에 대한 갯수를 가져옵니다. 
- 대본 갯수
- 게시글 갯수
- 댓글 갯수

[#102] 각 페이지 갯수 가져오기

---

src/main/java/com/speech/up/record/controller/RecordController.java
src/main/java/com/speech/up/record/entity/RecordEntity.java
src/main/java/com/speech/up/record/service/RecordService.java
src/main/java/com/speech/up/record/service/dto/RecordGetDto.java
src/main/java/com/speech/up/report/controller/ReportController.java
src/main/java/com/speech/up/report/repository/ReportRepository.java
src/main/java/com/speech/up/report/service/ReportService.java
src/main/resources/static/css/board-write.css
src/main/resources/static/css/header-style.css
src/main/resources/static/css/home-style.css
src/main/resources/static/css/land-style.css
src/main/resources/static/css/script-style.css
src/main/resources/static/css/script-write.css
src/main/resources/static/css/signIn-style.css
src/main/resources/static/scriptPage/js/addRecordingToList.js
src/main/resources/static/scriptPage/js/addTokenSession.js
src/main/resources/static/scriptPage/js/analyticRecord.js
src/main/resources/static/scriptPage/js/boardModify.js
src/main/resources/static/scriptPage/js/boardWrite.js
src/main/resources/static/scriptPage/js/checkBoardOwner.js
src/main/resources/static/scriptPage/js/loadLocalRecord.js
src/main/resources/static/scriptPage/js/localStoragePath.js
src/main/resources/static/scriptPage/js/record.js
src/main/resources/static/scriptPage/js/reply.js
src/main/resources/static/scriptPage/js/saveRecord.js
src/main/resources/static/scriptPage/js/scriptList.js
src/main/resources/static/scriptPage/js/scriptWrite.js
src/main/resources/static/scriptPage/js/userDelete.js
src/main/resources/static/scriptPage/js/userMe.js
src/main/resources/templates/script.html

- 분석 중 로딩화면 구현
- 분석 완료 시 record 테이블의 isAnalyzed 값 true 변환
- report 불러오기 기능 구현 (데이터만 받아오면 됨)
- record 테이블에 is_analyzed boolean not null 추가해주세요

[#82] feature : 분석 중 로딩화면 및 상태변환

---

src/test/java/com/speech/up/script/service/ScriptServiceTest.java

[#107] feature : Script 테스트 코드 추가

---

src/main/resources/static/scriptPage/js/loadLocalRecord.js

- 분석 요청시 recordId 가 scriptId 로 지정되는 오류 수정함

[#76] fix : 오류 사항 수정

---

src/main/java/com/speech/up/auth/filter/JwtAuthenticationFilter.java
src/main/java/com/speech/up/auth/handler/OAuth2SuccessHandler.java
src/main/java/com/speech/up/auth/provider/KakaoProvider.java
src/main/resources/static/css/script-style.css
src/main/resources/static/scriptPage/js/analyticRecord.js
src/main/resources/templates/home.html
src/main/resources/templates/report.html
src/main/resources/templates/script.html

- kakao provider 에서 properties 를 mapping 하는 로직을 수정했습니다.
- 분석 결과를 새로운 페이지 이동 방식에서 새로운 윈도우를 팝업으로 여는 방식으로 변경했습니다.

[#113] refactor : kakao properties 맵핑 로직 수정 및 분석 결과 열람 방식 변경

---

Dockerfile
build.gradle

[#111] 배포를 위한 환경설정

---

src/main/java/com/speech/up/UpApplication.java
src/main/java/com/speech/up/demo/HomePageController.java
src/main/resources/application.yaml
src/main/resources/templates/map.html

- 앱 키 노출로 인해 키 삭제 후 새로 만들고 수정했습니다.

[#127] fix! : appkey 노출로 인한 변경

---

src/main/java/com/speech/up/auth/service/implement/OAuth2UserServiceImplement.java
src/main/java/com/speech/up/user/entity/UserEntity.java
src/main/java/com/speech/up/user/repository/UserRepository.java
src/main/java/com/speech/up/user/service/UserScheduling.java

장기 미접속 (일주일) 유저를 주기적으로 삭제하는 프로그램입니다. 
isUse를 0으로 바꿔야 하는데 그냥 삭제하는 코드입니다. 
추후 0으로 바꾸는 repository 추가해야 하겠습니다.

[#139] 장기 미접속 유저 삭제

---

src/main/java/com/speech/up/admin/controller/AdminController.java
src/main/java/com/speech/up/admin/controller/AdminPageController.java
src/main/java/com/speech/up/auth/provider/GithubProvider.java
src/main/java/com/speech/up/auth/provider/GoogleProvider.java
src/main/java/com/speech/up/auth/provider/KakaoProvider.java
src/main/java/com/speech/up/auth/service/implement/UserAuthorizationType.java
src/main/java/com/speech/up/user/controller/UserController.java
src/main/java/com/speech/up/user/repository/UserRepository.java
src/main/java/com/speech/up/user/service/UserService.java
src/main/java/com/speech/up/user/service/dto/UserGetInfoDto.java
src/main/resources/static/css/admin-view.css
src/main/resources/static/scriptPage/js/adminUserHandler.js
src/main/resources/static/scriptPage/js/checkAdministration.js
src/main/resources/templates/admin-page.html

- 관리자 페이지 구현 완료 
- 추후 리펙토링 마무리 하면 될 것 같습니다.

[#146]관리자 페이지 구현 완료

---

src/main/java/com/speech/up/auth/config/WebSecurityConfig.java
src/main/resources/static/scriptPage/js/map.js
src/main/resources/static/scriptPage/js/userMe.js
src/main/resources/templates/myPage.html

- 스피치 학원이 없을 경우 페이지를 닫는 코드 추가
- 마이페이지 수정
- 시큐리티 map 추가

[#127] 스피치 학원 없을 경우 페이지를 닫는 코드 추가

---

build.gradle
src/main/java/com/speech/up/board/controller/BoardController.java
src/main/java/com/speech/up/demo/BoardPageController.java
src/main/java/com/speech/up/demo/HomePageController.java
src/main/java/com/speech/up/demo/RegisterPageController.java
src/main/java/com/speech/up/demo/ReportPageController.java
src/main/java/com/speech/up/demo/ScriptPageController.java
src/main/java/com/speech/up/record/controller/RecordController.java
src/main/java/com/speech/up/reply/controller/ReplyController.java
src/main/java/com/speech/up/user/controller/UserController.java

[#151] javadoc 작성

---

src/main/java/com/speech/up/reply/controller/ReplyController.java
src/main/java/com/speech/up/reply/service/ReplyService.java
src/test/java/com/speech/up/board/service/BoardServiceTest.java
src/test/java/com/speech/up/reply/service/ReplyServiceTest.java
src/test/java/com/speech/up/script/service/ScriptServiceTest.java

테스트 코드 추가하였습니다.
- ReplyTest
- BoardTest
- ScriptTest
- ReplyService 의 메소드 변경하였습니다.
getBoardCount -> getReplyCount

[#157] 테스트 코드 추가

---

src/main/resources/templates/board.html
src/main/resources/templates/script.html

[#180] feature : 오디오 파일 체크 추가

---

build.gradle
src/main/java/com/speech/up/reply/controller/ReplyController.java
src/main/resources/application-test.yaml
src/test/java/com/speech/up/UpApplicationTests.java
src/test/java/com/speech/up/board/controller/BoardControllerTest.java
src/test/java/com/speech/up/board/service/BoardServiceTest.java
src/test/java/com/speech/up/record/controller/RecordControllerTest.java
src/test/java/com/speech/up/reply/service/ReplyServiceTest.java
src/test/java/com/speech/up/report/controller/ReportControllerTest.java
src/test/java/com/speech/up/report/repository/ReportRepositoryTest.java
src/test/java/com/speech/up/report/service/ReportServiceTest.java
src/test/java/com/speech/up/script/controller/ScriptControllerTest.java
src/test/java/com/speech/up/script/service/ScriptServiceTest.java
src/test/java/com/speech/up/user/controller/UserControllerTest.java
src/test/java/com/speech/up/user/repositiory/UserRepositoryTest.java
src/test/java/com/speech/up/user/service/UserServiceTest.java

테스트 코드는 추가하였습니다. 
Mock 기반 테스트라 커버리지에 추가되지 않습니다.

[#54] 테스트 코드 추가

---

src/main/resources/static/css/admin-view.css
src/main/resources/static/css/home-style.css
src/main/resources/static/css/report-style.css
src/main/resources/static/js/userMe.js
src/main/resources/templates/home.html
src/main/resources/templates/report.html
src/main/resources/templates/script.html

Feature/#178/home page UI

---

src/test/java/com/speech/up/auth/provider/GithubProviderTest.java
src/test/java/com/speech/up/auth/provider/GoogleProviderTest.java
src/test/java/com/speech/up/auth/provider/JwtProviderTest.java
src/test/java/com/speech/up/auth/provider/KakaoProviderTest.java
src/test/java/com/speech/up/auth/provider/ProviderTest.java

[#189] 테스트 코드 추가

---

build.gradle
src/test/java/com/speech/up/demo/BoardPageControllerTest.java
src/test/java/com/speech/up/demo/HomePageControllerTest.java
src/test/java/com/speech/up/demo/RegisterPageControllerTest.java
src/test/java/com/speech/up/demo/ReportPageControllerTest.java
src/test/java/com/speech/up/demo/ScriptPageControllerTest.java

[#54] feat: demo test code

---

src/test/java/com/speech/up/auth/entity/CustomOAuth2UserTest.java
src/test/java/com/speech/up/auth/filter/JwtAuthenticationFilterTest.java
src/test/java/com/speech/up/auth/handler/OAuth2SuccessHandlerTest.java
src/test/java/com/speech/up/reply/service/ReplyServiceTest.java

[#54] coverage 를 위한 테스트 코드 수정

---

src/main/java/com/speech/up/admin/entity/StatisticsEntity.java
src/main/java/com/speech/up/auth/config/WebSecurityConfig.java
src/main/java/com/speech/up/auth/provider/GithubProvider.java
src/main/java/com/speech/up/auth/provider/GoogleProvider.java
src/main/java/com/speech/up/auth/provider/KakaoProvider.java
src/main/java/com/speech/up/auth/service/implement/UserAuthorizationType.java
src/main/java/com/speech/up/common/enums/UserStatusCode.java
src/main/java/com/speech/up/demo/BannedController.java
src/main/java/com/speech/up/user/controller/UserController.java
src/main/java/com/speech/up/user/entity/UserEntity.java
src/main/java/com/speech/up/user/repository/UserRepository.java
src/main/java/com/speech/up/user/service/UserService.java
src/main/java/com/speech/up/user/service/dto/UserUpdateDto.java
src/main/resources/static/js/checkBanned.js
src/main/resources/static/js/userMe.js
src/main/resources/templates/banned.html
src/test/java/com/speech/up/auth/provider/GithubProviderTest.java
src/test/java/com/speech/up/auth/provider/GoogleProviderTest.java
src/test/java/com/speech/up/auth/provider/KakaoProviderTest.java
src/test/java/com/speech/up/demo/BannedControllerTest.java
src/test/java/com/speech/up/user/controller/UserControllerTest.java
src/test/java/com/speech/up/user/service/UserServiceTest.java

[#169] 밴 사용자 적용

---

src/main/resources/templates/board-detail.html

[#178] fix: 빈 텍스트 댓글 추가 오류 수정

---

src/main/java/com/speech/up/api/etri/dto/AiRequest.java
src/main/java/com/speech/up/auth/handler/OAuth2SuccessHandler.java
src/test/java/com/speech/up/common/aspect/LoggingAspectTest.java

[#169] 테스트 코드 수정, 미사용 코드 삭제
